title: Blog | Carter Liebman
email: design@carterliebman.com
description: >- # this means to ignore newlines until "baseurl:"
    The ramblings of a Chicago-based computer geek.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carterliebman.com"
twitter_username: CarterLiebman
github_username:  CarterLiebmen

# Build settings
theme: minima
plugins:
  - jekyll-feed