title: Blog | Carter Liebman
email: design@carterliebman.com
description: >- # this means to ignore newlines until "baseurl:"
    The ramblings of a Chicago-based computer geek.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
twitter_username: CarterLiebman
github_username:  CarterLiebman
instagram_username: CarterLiebman 

# Build settings
remote_theme: "dracula/gh-pages"
plugins:
  - jekyll-feed
